# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c5e32ac9c1ae2896f72a34ce6ac01e7069749ca92d5fdfb6f1fbdef28a178a2ebd6c1f787a6c2eb46d5f65d03b173f66c52650177cc9c033a961c3a8ce9a15c7
  twilio_account_sid: <%= ENV["TWILIO_ACCOUNT_SID"] %>
  twilio_auth_token: <%= ENV["TWILIO_AUTH_TOKEN"] %>

test:
  secret_key_base: 2c355bce003ed1f695d55add35fbf8b8b43260fe10b74d2858764b1c75f4739dff1a11681b7cd6860c0932cd95dc451cf550001d3354cc3e357e65ba6af3e4f2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  twilio_account_sid: <%= ENV["TWILIO_ACCOUNT_SID"] %>
  twilio_auth_token: <%= ENV["TWILIO_AUTH_TOKEN"] %>

