# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 29863ad45cb26f3e17f46b7e8deef6abe287f5da78c093caaa53067d2b8476e270a2d49b66005f03406e3695f97cf4de8927dd5941f065680803da195f9375b7

test:
  secret_key_base: 2c355bce003ed1f695d55add35fbf8b8b43260fe10b74d2858764b1c75f4739dff1a11681b7cd6860c0932cd95dc451cf550001d3354cc3e357e65ba6af3e4f2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  foursquare_id: <%= ENV["FOURSQUARE_ID"] %>
  foursquare_secret: <%= ENV["FOURSQUARE_SECRET"] %>
