# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

# Preseed.create(desc: "Become aware of fire evacuation and earthquake safety plans for all of the buildings you occupy regularly.", event: "Prequake")
# Preseed.create(desc: "Pick safe places in each room of your home, workplace and/or school. A safe place could be under a piece of furniture or against an interior wall away from windows, bookcases or tall furniture that could fall on you.", event: "Prequake")
# Preseed.create(desc: "Practice 'drop, cover and hold on' in each safe place. If you do not have sturdy furniture to hold on to, sit on the floor next to an interior wall and cover your head and neck with your arms.", event: "Prequake")
# Preseed.create(desc: "Keep a flashlight and sturdy shoes by each person’s bed in case the earthquake strikes in the middle of the night.", event: "Prequake")
# Preseed.create(desc: "Keep and maintain an emergency supplies kit (water, batteries, cash) in an easy-to-access location.", event: "Prequake")

# Preseed.create(desc: "The disaster may continue. Expect and prepare for potential aftershocks, landslides or even a tsunami. Tsunamis are often generated by earthquakes.", event: "Postquake")
# Preseed.create(desc: "Each time you feel an aftershock, drop, cover and hold on. Aftershocks frequently occur minutes, days, weeks and even months following an earthquake.", event: "Postquake")
# Preseed.create(desc: "Check yourself for injuries and get First Aid, if necessary, before helping injured or trapped persons.", event: "Postquake")
# Preseed.create(desc: "Look quickly for damage in and around your home and get everyone out if your home is unsafe.", event: "Postquake")
# Preseed.create(desc: "Be careful when driving after an earthquake and anticipate traffic light outages.", event: "Postquake")
# Preseed.create(desc: "Watch out for fallen power lines or broken gas lines and stay out of damaged areas.", event: "Postquake")


