# L.mapbox.accessToken = 'pk.eyJ1IjoiZ3JlZ29zZiIsImEiOiIxMDRkNWRjNzQ0ODkzNzE2ZTE2YzQ3OGIxMzFjNzZmMCJ9.OA1rNWlN2qWZT03zyD0zGQ'
# geolocate = document.getElementById('geolocate')
# map = L.mapbox.map('map', 'mapbox.streets')
# myLayer = L.mapbox.featureLayer().addTo(map)
# if !navigator.geolocation
#   geolocate.innerHTML = 'Geolocation is not available'
# else

#   geolocate.onclick = (e) ->
#     e.preventDefault()
#     e.stopPropagation()
#     map.locate()
#     return

# map.on 'locationfound', (e) ->
#   map.fitBounds e.bounds
#   myLayer.setGeoJSON
#     type: 'Feature'
#     geometry:
#       type: 'Point'
#       coordinates: [
#         e.latlng.lng
#         e.latlng.lat
#       ]
#     properties:
#       'title': 'Here I am!'
#       'marker-color': '#ff8888'
#       'marker-symbol': 'star'
#   # And hide the geolocation button
#   geolocate.parentNode.removeChild geolocate
#   return
# map.on 'locationerror', ->
#   geolocate.innerHTML = 'Position could not be found'
#   return

# ---
# generated by js2coffee 2.1.0